#pragma once
#include <cstdio>
#include <cstdlib>
#include <vector>
// Called after query timing ends. File was generated by int64 Dijkstra on G.
static int supplement_oracle_check(const int *actual,int n) {
    const char *path=std::getenv("L3_SUPPLEMENT_ORACLE");
    if(!path) return 0;
    FILE *f=std::fopen(path,"rb"); if(!f){std::perror(path);std::exit(2);}
    std::vector<int>d(n);bool ok=std::fread(d.data(),sizeof(int),n,f)==size_t(n) && std::fgetc(f)==EOF;
    std::fclose(f);if(!ok){fprintf(stderr,"ORACLE_SIZE_ERROR\n");std::exit(2);}
    for(int u=0;u<n;++u) if(actual[u]!=d[u]){fprintf(stderr,"ORACLE_MISMATCH vertex=%d actual=%d expected=%d\n",u,actual[u],d[u]);return 1;}
    printf("WIDE_ORACLE vertices=%d correct=1\n",n);return 0;
}
