#pragma once

#ifndef MLMQ_WORKER_THREADS
#define MLMQ_WORKER_THREADS 512
#endif
#if (MLMQ_WORKER_THREADS != 512 && MLMQ_WORKER_THREADS != 384 && MLMQ_WORKER_THREADS != 320)
#error "Only baseline512 and isolated worker384/320 are supported"
#endif
#define THREAD_NUM_PER_BLOCK MLMQ_WORKER_THREADS
#define ALIGN_THREAD_PER_BLOCK THREAD_NUM_PER_BLOCK
#define WORK_BLOCK_NUM 79

#define WARP_SIZE 32
#define WARP_NUM_PER_BLOCK (THREAD_NUM_PER_BLOCK / WARP_SIZE)
#define WARP_NUM_PER_SM (WARP_NUM_PER_BLOCK * BLOCK_NUM / SM_NUM)
#define WARP_NUM (BLOCK_NUM * WARP_NUM_PER_BLOCK)
#define BLOCK_PER_SM (BLOCK_NUM / SM_NUM)
#define WORK_WARP_NUM (WORK_BLOCK_NUM * WARP_NUM_PER_BLOCK)

#define FRE (1.35 * 1000 * 1000)
